### ISSUE TITLE
[BUG] Uncaught TypeError: this.owner.onMarkdownScroll is not a function

### ISSUE THREAD

**Issue by wwjCMP** [Quorafind/Obsidian-Card-Library#22]
Uncaught TypeError: this.owner.onMarkdownScroll is not a function
    at t.handleScroll (app.js:1:1643466)
    at t.onScroll (app.js:1:1643403)
    at HTMLDivElement.<anonymous> (app.js:1:1643068)

**Comment by wwjCMP** [comment]
![image](https://github.com/user-attachments/assets/a5a1d06e-2011-43aa-85a9-228bc380141e)

**Comment by wwjCMP** [comment]
点击canvas中的文件就会出现错误
